"""add deleted_at field for soft delete

Revision ID: bb1f6ec84dc3
Revises: 2e767e77399b
Create Date: 2026-09-27 13:32:39.797179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1f6ec84dc3'
down_revision: Union[str, Sequence[str], None] = '2e767e77399b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('project_categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('skill_categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('skills', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('technologies', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technologies', 'deleted_at')
    op.drop_column('skills', 'deleted_at')
    op.drop_column('skill_categories', 'deleted_at')
    op.drop_column('projects', 'deleted_at')
    op.drop_column('project_categories', 'deleted_at')
    op.drop_column('admins', 'deleted_at')
    # ### end Alembic commands ###
